export const staticAmpPrivateOffer = {
  DealBasicDetails: {
    DealId: 19899,
    DealReferenceID: "bb1d04e5-de22-4600-914b-ddc3af5e4e03",
    DealCode: "",
    DealName: "Trinity Enterprises- 1 month contract",
    Description:
      "This is the Private offer between Trinity Enterprises and SaaSify",
    Salesagent: "Niharika",
    ProviderID: 68,
    NotificationRecipients: "samay.joshi@saasify.ai",
    PreparedBy: "niharika.shrivastava@saasify.ai",
    DealStatusID: 2,
    DealStatus: "Published",
    SaaSifySubscriptionID: null,
    PrivateOfferLink:
      "https://azuremarketplace.microsoft.com/commercial?QuoteID=b90b634261bc",
    IsActive: true,
    TenantID: 1000002,
    IsDealFromCRM: false,
    EnablePrivateOfferAPIIntegration: true,
    PrivateOfferID: 12061,
    AdditionalParametersJson: '[{"Name":"Sales Region","Value":"EMEA"}]',
    SubscriptionName: null,
    SalesagentPrimaryContact: "niharika.shrivastava@saasify.ai",
    SalesTeamNotes: null,
    IsReseller: false,
    ResellerType: null,
    CustomerEmail: "niharika.shrivastava@spektrasystems.com",
    CustomerName: "Spektra Systems",
    AddressLine1: "620 SW 5th Avenue Suite 400",
    AddressLine2: null,
    State: "California",
    Country: "United States of America ",
    ZipCode: "90001",
    StartDateType: "Accepted Date",
    StartDate: "2025-02-15T10:00:00",
    EndDate: "2025-03-31T12:10:00",
    AcceptedDate: "2025-02-20T04:50:00",
    IsDealCreatedFromAPI: false,
    AWSAgreementId: null,
    SelectedCRMName: "",
    CRMMappingId: 0,
    OfferCreatedDate: "2025-02-15T11:31:24.44",
    StepInformation: null,
    ProviderName: "AMP",
    MaxFilesSize: null,
    MaxFileCount: null,
    AWSCPOfferData:
      '[{"OfferID":"private-offer\\/ef5e8a2b-28d0-4e40-8f7c-fefcae6aa3b6","OfferName":"","OfferCreatedDate":"","OfferExpiryDate":"","ProductId":"","ProductName":"","Agreement":"{\\"AgreementID\\":\\"\\",\\"ServiceStartDate\\":\\"Jan  1 1900 12:00AM\\",\\"ServiceEndDate\\":\\"Jan  1 1900 12:00AM\\",\\"OfferID\\":\\"private-offer\\\\\\/ef5e8a2b-28d0-4e40-8f7c-fefcae6aa3b6\\",\\"BuyerAccountId\\":\\"\\",\\"AcceptanceTime\\":\\"Jan  1 1900 12:00AM\\",\\"SubscriptionName\\":\\"\\",\\"AutoRenew\\":\\"\\",\\"AgreementType\\":\\"\\"}"}]',
  },
  DealCRMDetails: null,
  DealPurchaserDetails: {
    DealPurchaserId: 14305,
    DealId: 19899,
    DealReferenceID: "bb1d04e5-de22-4600-914b-ddc3af5e4e03",
    CustomerName: "Trinity Enterprises",
    Email: "niharika.shrivastava@spektrasystems.com",
    AddressLine1: "620 SW 5th Avenue Suite 400",
    AddressLine2: null,
    Zip: "90001",
    ContactJson:
      "aruljothi.kuppusamy@saasify.ai,prithiviraj.murugesan@saasify.ai",
    CustomerAccountId:
      "422dc48d-d91c-54fd-3763-a3eb3fb60e98:e651facf-86a5-4e87-b237-b96e765a8a24_2019-05-31",
    CustomerTenantID: "d1201cf3-cb52-4808-a742-33c281aaea3b",
    Description: "This is for testing",
    SaaSifyCustomerID: null,
    TenantId: 1000002,
    IsExistingDetailsLinked: null,
    Company: "",
    CustomerNote: "",
    CustomerContactName: "",
    MarketplaceSellerID: "",
    ISVSalesNote: "",
    CustomerFullAddress:
      "620 SW 5th Avenue Suite 400,Uttar Pradesh,India,97204",
    Country: "United States of America",
    State: "California",
    ResellerContactJson: "",
  },
  DealTermDetails: {
    DealTermId: 13286,
    DealId: 19899,
    DealReferenceId: null,
    ProductID: 10727,
    StartDateType: "Accepted Date",
    StartDate: "2025-02-15T00:00:00",
    EndDate: "2025-03-31T00:00:00",
    AcceptedDate: "2025-02-20T00:00:00",
    IsCustomBilling: true,
    BillingName: null,
    ExpirationDate: "",
    AgreementFileName: null,
    AgreementURL:
      "http://api.saaskit.com/api/documents/cloudsaaskit/privateoffers/customereula/D383AC6A-74FC-4689-B50B-68D09B174F28",
    TenantId: 1000002,
    AWSOfferIdentifier: null,
    CreatedDate: "2025-02-15T11:26:08.54",
    OfferTermDetailsJson: null,
    GCPOfferIdentifier: null,
    IsSelectedStandardEULA: false,
    LegalTermTypeID: null,
    LegalTermType: null,
    LegalTermFiles: "",
    AMPOfferIdentifier: "private-offer/ef5e8a2b-28d0-4e40-8f7c-fefcae6aa3b6",
    IsFPSEnabled: false,
    IsRenewal: true,
    RenewalType: null,
    AgreementEndDate: null,
    PrivateOfferTypeID: null,
    AgreementStartDate: null,
    IsFutureDateAgreementExists: null,
    AgreementData:
      '{"extraData":{"sellerAccountCode":"86850A8C","SellerAccountID":1,"sellerAccountName":"AMP USA - Private Offer"}}',
    CustomerAccountId:
      "422dc48d-d91c-54fd-3763-a3eb3fb60e98:e651facf-86a5-4e87-b237-b96e765a8a24_2019-05-31",
    CustomMetricsID: 2,
    CustomMetricsValue: null,
    PrivateOfferType: null,
    PrivateOfferTypeDescription: null,
    RenewalTypeAWSValue: null,
    AgreementID: null,
    MarketplaceProductId: "1c9f3ceb-d9f4-45cc-b4c4-0493bad6503c",
  },
  DealPricingDetails: {
    DealPricingId: 11535,
    DealId: 19899,
    DealReferenceId: "bb1d04e5-de22-4600-914b-ddc3af5e4e03",
    PricingJson:
      '{"PriceType":"Absolute Price","ProductID":10727,"PlanID":18629,"PrivateOfferName":"Trinity Enterprises- 1 month contract","PricingModel":"Flat Rate","IsMonthlyEnabled":true,"IsAnnualEnabled":false,"IsMonthlyPrice":0.001,"IsAnnualPrice":null,"IsTwoyearEnabled":false,"IsTwoyearPrice":null,"IsThreeyearEnabled":false,"IsThreeyearPrice":null,"FreeTrail":false,"Discount":null,"SelleraccountID":1,"IsMinimumUsersEnabled":false,"MinimumUsers":null,"IsMaximumUsersEnabled":false,"MaximumUsers":null,"PlanProviderMonthlyPaymentFrequencyId":1,"PlanProvider2YearPaymentFrequencyId":null,"PlanProvider3YearPaymentFrequencyId":null,"PlanProviderAnnualPaymentFrequencyId":null,"PlansJson":null,"SchedulePrice":null,"DimensionsPrice":null,"PublicPlanProviderMonthlyBillingPrice":0.012,"PublicPlanProviderAnnualBillingPrice":0.012,"PublicPlanProvider2YearBillingPrice":0.012,"PublicPlanProvider3YearBillingPrice":null,"MeterData":"[{\\"MeterProviderID\\":37459,\\"MeterProviderPricingDetailID\\":35262,\\"MeterID\\":37021,\\"MeterName\\":\\"automated_reporting\\",\\"MeterDescription\\":\\"Automated Reporting\\",\\"UnitOfMeasure\\":\\"per report\\",\\"ProviderReference\\":\\"automated_reporting\\",\\"Price\\":\\"1\\",\\"IsActive\\":true,\\"AdditionalDimension\\":null,\\"DefaultforUsuageRequest\\":null,\\"MonthlyQuantityIncludedInBase\\":10,\\"AnnualQuantityIncludedInBase\\":0,\\"IsMonthlyUnlimitedQuantity\\":null,\\"IsAnnuallyUnlimitedQuantity\\":null,\\"TwoYearQuantityIncludedInBase\\":0,\\"ThreeYearQuantityIncludedInBase\\":0,\\"IsTwoYearUnlimitedQuantity\\":null,\\"IsThreeYearUnlimitedQuantity\\":null,\\"IsDeleteButtonEnabled\\":true,\\"MarketplaceDescription\\":null,\\"isPriceTouched\\":true}]"}',
    SelleraccountID: 1,
    TenantId: 1000002,
    StepInformation: null,
    TotalContractValue: null,
    MarketplaceFeePercent: null,
    TotalContractValueCurrency: null,
    CreatedDateInMarketplace: null,
  },
  DealPublishedErrorDetails: [],
  CRMConfiguration: {
    Name: "Salesforce",
    IsEnable: true,
    ProviderName: "AMP",
  },
};
