export const privateOfferPayload = {
    "Name": "",
    "Description": null,
    "DealCode": "",
    "Salesagent": "",
    "ProviderID": null,
    "NotificationRecipients": "",
    "PreparedBy": "",
    "ProductType": "",
    "DealStatusID": 1,
    "IsActive": true,
    "DealReferenceID": "",
    "CRMName": null,
    "CRMMappingID": null,
    "IsDealFromCRM": true,
    "ResellerType": null,
    "CRMConnection": null,
    "IsReseller": false,
    "StepInformation": "BasicInformation"
}
