export const staticPrivateOffer = {
  DealBasicDetails: {
    DealId: 19763,
    DealReferenceID: "a54ce797-0464-4009-a8fa-9d4f032f12dc",
    DealCode: null,
    DealName: "Globex Corporation-1 year contract",
    Description: "created this private offer from Salesforce instance",
    Salesagent: "srinivas",
    ProviderID: 69,
    NotificationRecipients:
      "indrasena.bijjala@spektrasystems.com,prasad.yalla@spektrasystems.com,nithin.nalli@spektrasystems.com,kakaraparthi.srinivas@spektrasystems.com,skandasharma.hv@spektrasystems.com",
    PreparedBy: "44.srinivas@gmail.com",
    DealStatusID: 2,
    DealStatus: "Published",
    SaaSifySubscriptionID: "093ca507-3573-49fa-99aa-51e073455165",
    PrivateOfferLink:
      "https://aws.amazon.com/marketplace/saas/ordering?productId=prod-kxj5cqff2cgwk&offerId=offer-csw5mpwgfo4cw",
    IsActive: true,
    TenantID: 1000002,
    IsDealFromCRM: true,
    EnablePrivateOfferAPIIntegration: true,
    PrivateOfferID: 11998,
    AdditionalParametersJson: '[{"Name":"Tag1","Value":"My Tag"}]',
    SubscriptionName: "QA-Tier-Contact with consumpiton-S3_WVzLzPBfko1_093CA",
    SalesagentPrimaryContact: "44.srinivas@gmail.com",
    SalesTeamNotes: null,
    IsReseller: false,
    ResellerType: null,
    CustomerEmail: "vikash.sharma@spektrasystems.com",
    CustomerName: "AWS SF-002",
    AddressLine1: "4-8-34",
    AddressLine2: null,
    State: "Colorado",
    Country: "United States of America",
    ZipCode: "453213",
    StartDateType: null,
    StartDate: null,
    EndDate: null,
    AcceptedDate: null,
    IsDealCreatedFromAPI: true,
    AWSAgreementId: "agmt-854cwo7pstymm06yef5i4o1n1",
    SelectedCRMName: "SalesForce",
    CRMMappingId: 0,
    OfferCreatedDate: "2024-11-28T13:14:51.463",
    StepInformation: null,
    ProviderName: "AWS",
    MaxFilesSize: 10485760,
    MaxFileCount: 5,
    AWSCPOfferData:
      '[{"OfferID":"offer-csw5mpwgfo4cw","OfferName":"","OfferCreatedDate":"","OfferExpiryDate":"","ProductId":"","ProductName":"","Agreement":"{\\"AgreementID\\":\\"agmt-854cwo7pstymm06yef5i4o1n1\\",\\"ServiceStartDate\\":\\"Oct 28 2024  5:46AM\\",\\"ServiceEndDate\\":\\"Oct 28 2024  6:28AM\\",\\"OfferID\\":\\"offer-csw5mpwgfo4cw\\",\\"BuyerAccountId\\":\\"556258033461\\",\\"AcceptanceTime\\":\\"Oct 28 2024  5:46AM\\",\\"SubscriptionId\\":\\"093CA507-3573-49FA-99AA-51E073455165\\",\\"SubscriptionName\\":\\"QA-Tier-Contact with consumpiton-S3_WVzLzPBfko1_093CA\\",\\"AutoRenew\\":\\"\\",\\"AgreementType\\":\\"\\"}"}]',
  },
  DealCRMDetails: {
    DealCRMMappingID: 7373,
    DealID: 19842,
    DealReferenceID: "215b3cee-0840-4d30-b4d7-ea5174dbad97",
    CRMLookUpJson: null,
    CRMAccountID: null,
    CRMOpportunityID: "a0CEa00002dH9SRMA0",
    CRMOpportunityJson: '{"Id":"a0CEa00002dH9SRMA0"}',
    TenantID: 1000002,
    SaaSifySubscriptionID: null,
    PrivateOfferLink: null,
    OfferIdentifier: null,
    CRMDealStatus: null,
    ProviderName: null,
    IsReseller: null,
  },
  DealPurchaserDetails: {
    DealPurchaserId: 14267,
    DealId: 19842,
    DealReferenceID: "215b3cee-0840-4d30-b4d7-ea5174dbad97",
    CustomerName: "Scantech",
    Email: "sri.vidhya@spektrasystems.com",
    AddressLine1: null,
    AddressLine2: null,
    Zip: null,
    ContactJson: "test1@testing.com,prafull.bhandari@spektrasystems.com",
    CustomerAccountId: "556258033461",
    CustomerTenantID: null,
    Description: null,
    SaaSifyCustomerID: null,
    TenantId: 1000002,
    IsExistingDetailsLinked: false,
    Company: "Scantech",
    CustomerNote: null,
    CustomerContactName: null,
    MarketplaceSellerID: null,
    ISVSalesNote: null,
    CustomerFullAddress: null,
    Country: null,
    State: null,
    ResellerContactJson: null,
  },
  DealTermDetails: {
    DealTermId: 13250,
    DealId: 19842,
    DealReferenceId: "215b3cee-0840-4d30-b4d7-ea5174dbad97",
    ProductID: 11585,
    StartDateType: null,
    StartDate: null,
    EndDate: null,
    AcceptedDate: null,
    IsCustomBilling: true,
    BillingName: "12",
    ExpirationDate: "2024-10-31T01:02:00",
    AgreementFileName:
      "250842a609e4429c881c30f27671830f_276a4570bffd413692c6173892ec5517_Public_eula.pdf",
    AgreementURL:
      "https://saasifyawsuploads.s3.amazonaws.com/CloudSaaSKit/250842a609e4429c881c30f27671830f_276a4570bffd413692c6173892ec5517_Public_eula.pdf",
    TenantId: 1000002,
    AWSOfferIdentifier: "offer-5oaxl76fp5f2i",
    CreatedDate: "2024-10-29T09:54:46.573",
    OfferTermDetailsJson: null,
    GCPOfferIdentifier: null,
    IsSelectedStandardEULA: false,
    LegalTermTypeID: 4,
    LegalTermType: "Public",
    LegalTermFiles: null,
    AMPOfferIdentifier: null,
    IsFPSEnabled: true,
    IsRenewal: true,
    RenewalType: "Existing customer on AWS Marketplace",
    AgreementEndDate: null,
    PrivateOfferTypeID: 6,
    AgreementStartDate: "At Acceptance",
    IsFutureDateAgreementExists: false,
    AgreementData: null,
    CustomerAccountId: "556258033461",
    CustomMetricsID: 3,
    CustomMetricsValue: 1,
    PrivateOfferType: "NewPrivateOffer",
    PrivateOfferTypeDescription: "New private offer",
    RenewalTypeAWSValue: null,
    AgreementID: "",
    MarketplaceProductId: "prod-ofxlufiaxd7ry",
  },
  DealPricingDetails: {
    DealPricingId: 11498,
    DealId: 19842,
    DealReferenceId: "215b3cee-0840-4d30-b4d7-ea5174dbad97",
    PricingJson:
      '{"CustomOfferName":"AWS-reg-1 on BA with FPS","OfferName":"QA - Metle phase - TEST KP","IsMultipleDimensionSubscriptionEnabled":true,"IsSaaSContract":true,"IsZeroDollarPricingEnabled":null,"SchedulePrice":"[{\\"Date\\":\\"2024-10-29\\",\\"Price\\":100},{\\"Date\\":\\"2024-11-30\\",\\"Price\\":100},{\\"Date\\":\\"2025-01-04\\",\\"Price\\":100}]","ProductID":11585,"PlansJson":"[{\\"Name\\":\\"api_phase1\\",\\"Description\\":\\"Metle phase 1\\",\\"APIName\\":\\"api_phase1\\",\\"Price\\":0.0,\\"Units\\":1,\\"IsEditable\\":false,\\"PlanDetails\\":[{\\"Name\\":\\"api_phase1\\",\\"Description\\":\\"Metle phase 1\\",\\"APIName\\":\\"api_phase1\\",\\"IsSelected\\":true}],\\"PlanDescription\\":null,\\"MarketplaceDescription\\":\\"Narrating Metle phase 1\\",\\"IsCustomDimension\\":false},{\\"Name\\":\\"api_phase2\\",\\"Description\\":\\"Metle phase 2\\",\\"APIName\\":\\"api_phase2\\",\\"Price\\":0.0,\\"Units\\":2,\\"IsEditable\\":false,\\"PlanDetails\\":[{\\"Name\\":\\"api_phase2\\",\\"Description\\":\\"Metle phase 2\\",\\"APIName\\":\\"api_phase2\\",\\"IsSelected\\":true}],\\"PlanDescription\\":null,\\"MarketplaceDescription\\":\\"Narrating Metle phase 2\\",\\"IsCustomDimension\\":false}]","DimensionsPrice":"[{\\"Name\\":\\"api_addme1\\",\\"Description\\":\\"Additinal 1\\",\\"APIName\\":\\"api_addme1\\",\\"Price\\":1,\\"IsAdditionalDimension\\":false,\\"UnitOfMeasure\\":\\"Units\\",\\"PlanName\\":\\"Metle phase 1\\",\\"MarketplaceDescription\\":\\"Narrating Additinal 1\\"},{\\"Name\\":\\"api_addme2\\",\\"Description\\":\\"Additinal 2\\",\\"APIName\\":\\"api_addme2\\",\\"Price\\":1,\\"IsAdditionalDimension\\":false,\\"UnitOfMeasure\\":\\"Units\\",\\"PlanName\\":\\"Metle phase 1\\",\\"MarketplaceDescription\\":\\"Narrating Additinal 2\\"}]"}',
    SelleraccountID: 274,
    TenantId: 1000002,
    StepInformation: null,
    TotalContractValue: null,
    MarketplaceFeePercent: null,
    TotalContractValueCurrency: null,
    CreatedDateInMarketplace: "2024-10-29T10:40:24.99",
  },
  DealPublishedErrorDetails: [],
  CRMConfiguration: null,
};
