export const gcpStaticPrivateOffer = {
  DealBasicDetails: {
    DealId: 18920,
    DealReferenceID: "985b4c1b-3b94-4c10-a1d5-a6db0025345a",
    DealCode: "",
    DealName: "Star Vision Technologies- Flat Fee with Usage",
    Description:
      "This is the Private offer between Star Vision Technologies and SaaSify",
    Salesagent: "Syed",
    ProviderID: 173,
    NotificationRecipients: "skandasharma.hv@spektrasystems.com",
    PreparedBy: "syed.hyder@spektrsystems.com",
    DealStatusID: 2,
    DealStatus: "Published",
    SaaSifySubscriptionID: "1babedc3-152f-4b22-be11-08c65567cc94",
    PrivateOfferLink:
      "https://console.cloud.google.com/marketplace/private-offers/44e258fc-4742-4ac6-b3e7-236db32c26c7",
    IsActive: true,
    TenantID: 1000002,
    IsDealFromCRM: false,
    EnablePrivateOfferAPIIntegration: false,
    PrivateOfferID: 11815,
    AdditionalParametersJson: '[{"Name":"Sales Region","Value":"NA"}]',
    SubscriptionName:
      "providers/spektrasystems-devtest/entitlements/43f9191e-cd72-47ad-86af-cc6a711d8661",
    SalesagentPrimaryContact: "syed.hyder@spektrsystems.com",
    SalesTeamNotes: null,
    IsReseller: false,
    ResellerType: null,
    CustomerEmail: "syed.hyder@spektrasystems.com",
    CustomerName: "Trinity Enterprises",
    AddressLine1: "620 SW 5th Avenue Suite 400",
    AddressLine2: null,
    State: "New York",
    Country: "United States of America",
    ZipCode: "97204",
    StartDateType: null,
    StartDate: null,
    EndDate: null,
    AcceptedDate: null,
    IsDealCreatedFromAPI: false,
    AWSAgreementId: null,
    SelectedCRMName: "",
    CRMMappingId: 0,
    OfferCreatedDate: "2024-10-08T08:24:25.53",
    StepInformation: "OfferPricing",
    ProviderName: "GCP",
    MaxFilesSize: null,
    MaxFileCount: null,
    AWSCPOfferData:
      '[{"OfferID":"44e258fc-4742-4ac6-b3e7-236db32c26c7","OfferName":"","OfferCreatedDate":"","OfferExpiryDate":"","ProductId":"","ProductName":"","Agreement":"{\\"AgreementID\\":\\"\\",\\"ServiceStartDate\\":\\"Jan  1 1900 12:00AM\\",\\"ServiceEndDate\\":\\"Jan  1 1900 12:00AM\\",\\"OfferID\\":\\"44e258fc-4742-4ac6-b3e7-236db32c26c7\\",\\"BuyerAccountId\\":\\"\\",\\"AcceptanceTime\\":\\"Jan  1 1900 12:00AM\\",\\"SubscriptionId\\":\\"1BABEDC3-152F-4B22-BE11-08C65567CC94\\",\\"SubscriptionName\\":\\"providers\\\\\\/spektrasystems-devtest\\\\\\/entitlements\\\\\\/43f9191e-cd72-47ad-86af-cc6a711d8661\\",\\"AutoRenew\\":\\"\\",\\"AgreementType\\":\\"\\"}"}]',
  },
  DealCRMDetails: null,
  DealPurchaserDetails: {
    DealPurchaserId: 13864,
    DealId: 18920,
    DealReferenceID: "985b4c1b-3b94-4c10-a1d5-a6db0025345a",
    CustomerName: "Star Vision Technologies",
    Email: "syed.hyder@spektrasystems.com",
    AddressLine1: "620 SW 5th Avenue Suite 400",
    AddressLine2: null,
    Zip: "97204",
    ContactJson: "prithiviraj.murugesan@saasify.ai",
    CustomerAccountId: "0161BE-5517F4-14EB58",
    CustomerTenantID: "",
    Description: "",
    SaaSifyCustomerID: null,
    TenantId: 1000002,
    IsExistingDetailsLinked: null,
    Company: "",
    CustomerNote: "This is for testing",
    CustomerContactName: "Syed",
    MarketplaceSellerID: "",
    ISVSalesNote: "",
    CustomerFullAddress:
      "620 SW 5th Avenue Suite 400,New York,United States of America,97204",
    Country: "United States of America",
    State: "New York",
    ResellerContactJson: null,
  },
  DealTermDetails: {
    DealTermId: 12890,
    DealId: 18920,
    DealReferenceId: null,
    ProductID: 7994,
    StartDateType: null,
    StartDate: null,
    EndDate: null,
    AcceptedDate: null,
    IsCustomBilling: true,
    BillingName: null,
    ExpirationDate: "",
    AgreementFileName: null,
    AgreementURL:
      "http://api.saaskit.com/api/documents/cloudsaaskit/privateoffers/customereula/D383AC6A-74FC-4689-B50B-68D09B174F28",
    TenantId: 1000002,
    AWSOfferIdentifier: null,
    CreatedDate: "2024-10-08T08:12:26.397",
    OfferTermDetailsJson:
      '{"OfferID":7994,"OfferName":"reprint-ai.endpoints.spektrasystems-devtest.cloud.goog","OfferDescription":"Reprint AI","PlanName":"basic","PlanDescription":"Basic","PlanID":15012,"FeaturesList":[{"Feature":"CRM Support","Value":"Yes","IsAddDetailsAvailable":false,"DatesAndQuantitiesText":null},{"Feature":"Image Processing","Value":"Yes","IsAddDetailsAvailable":false,"DatesAndQuantitiesText":null},{"Feature":"Job Listings","Value":"No","IsAddDetailsAvailable":false,"DatesAndQuantitiesText":null}],"IsAutoRenewEnabled":false,"PricingModel":null,"PricingModelID":null,"PricingModelDescription":"Flat fee with usage","PaymentScheduleName":"Monthly","ContractDuration":2,"OfferAcceptanceDeadline":"2024-10-19","IsMetricDiscountsEnabled":null,"PricingOptionName":"FlatFeeWithUsage","CustomEulaDisplayName":null,"IsSelectedStandardEULA":true,"NumberOfRenewals":null,"SellerCode":"418848B2","SellerAccountID":247,"SellerAccountName":"GCPMinimalPermissionTest","OfferStartType":"Customer Acceptance","OfferStartDate":"2024-10-20","OfferEndDate":null,"PreviousData":{"offerTerm":{"productID":7994,"planID":15012,"planName":"basic","sellerCode":"418848B2","offerType":87,"previousOfferID":null,"productDetails":{"OfferID":7994,"OfferName":"reprint-ai.endpoints.spektrasystems-devtest.cloud.goog"},"PricingModel":null,"PricingModelID":null,"PricingModelDescription":"Flat fee with usage","usageBasedDiscountOnly":null,"paymentSchedule":"Monthly","contractDuration":2,"OfferAcceptanceDeadline":"2024-10-19","enableMetricDiscounts":null,"configureAutoRenew":false,"numberOfRenewals":null,"OfferStartType":"Customer Acceptance","OfferStartDate":"2024-10-20","OfferEndDate":null,"IsChangeOfferDurationEnabled":null,"Proration":"Off","paymentScheduleValue":"Monthly","featuresList":[{"Feature":"CRM Integration","Value":"Add details","IsAddDetailsAvailable":true,"DatesAndQuantitiesText":"54"},{"Feature":"CRM Support","Value":"Yes","IsAddDetailsAvailable":false,"DatesAndQuantitiesText":null},{"Feature":"Image Processing","Value":"Yes","IsAddDetailsAvailable":false,"DatesAndQuantitiesText":null},{"Feature":"Job Listings","Value":"No","IsAddDetailsAvailable":false,"DatesAndQuantitiesText":null}],"uploadedFiles":[],"selectedPlan":{"PlanID":15012,"PlanName":"basic","PlanDescription":"Basic","OfferID":7994,"PricingOptionName":"FlatFeeWithUsage","PricingOptionDescription":"Flat fee with usage","SubscriptionBillingPeriodID":"2","disabled":false,"PricingModelDescription":null},"savedOffer":{"OfferID":7994,"PlanID":15012},"AgreementFileName":null,"AgreementURL":null,"LegalTermTypeID":8,"CustomEulaDisplayName":null,"IsSelectedStandardEULA":true,"PrivateOfferType":"NewPrivateOffer"}},"IsChangeOfferDurationEnabled":null,"PrivateOfferType":"NewPrivateOffer","PreviousOfferID":null,"IsMultipleOrdersEnabled":false,"AmendPoData":null,"Proration":"Off"}',
    GCPOfferIdentifier: "44e258fc-4742-4ac6-b3e7-236db32c26c7",
    IsSelectedStandardEULA: false,
    LegalTermTypeID: 8,
    LegalTermType: "Standard",
    LegalTermFiles: null,
    AMPOfferIdentifier: null,
    IsFPSEnabled: false,
    IsRenewal: false,
    RenewalType: null,
    AgreementEndDate: null,
    PrivateOfferTypeID: 87,
    AgreementStartDate: null,
    IsFutureDateAgreementExists: null,
    AgreementData:
      '{"extraData":{"numberOfRenewals":null,"isAutoRenew":false,"CustomerAccountId":"0161BE-5517F4-14EB58"}}',
    CustomerAccountId: "0161BE-5517F4-14EB58",
    CustomMetricsID: 2,
    CustomMetricsValue: null,
    PrivateOfferType: "NewPrivateOffer",
    PrivateOfferTypeDescription: "New private offer",
    RenewalTypeAWSValue: null,
    AgreementID: null,
    MarketplaceProductId: null,
  },
  DealPricingDetails: {
    DealPricingId: 11124,
    DealId: 18920,
    DealReferenceId: "985b4c1b-3b94-4c10-a1d5-a6db0025345a",
    PricingJson:
      '{"IsFreeCreditEnabled":false,"UnusedCommittmentRuleType":"Rollover","MonthlyFlatFee":100,"MonthlyCommitment":0,"ProviderURL":"","TotalContractValue":"$200","InstallmentSchedule":[{"FreeCredit":null,"InstallmentDate":"2024-08-10","Flatfee":100,"DiscountOnUsage":"45%","Commitment":null,"DiscountOnCommitment":"45%","DiscountedCommitment":null,"IsInstallmentExpired":null},{"FreeCredit":null,"InstallmentDate":"2024-08-11","Flatfee":100,"DiscountOnUsage":"45%","Commitment":null,"DiscountOnCommitment":"45%","DiscountedCommitment":null,"IsInstallmentExpired":null}],"DiscountOnCommitment":45,"DiscountOnUsage":45,"MeterDiscounts":[],"PaymentScheduleValue":"Monthly","ContractDuration":2,"NumberOfRenewals":null,"OfferStartType":"Customer Acceptance","PricingOptionName":"FlatFeeWithUsage","PricingModel":null,"PlanID":15012,"PastAmount":0,"PastDiscount":0}',
    SelleraccountID: 247,
    TenantId: 1000002,
    StepInformation: null,
    TotalContractValue: "$200",
    MarketplaceFeePercent: null,
    TotalContractValueCurrency: "USD",
    CreatedDateInMarketplace: null,
  },
  DealPublishedErrorDetails: [],
  CRMConfiguration: {
    Name: "Salesforce",
    IsEnable: true,
    ProviderName: "GCP",
  },
};
