export enum FormButton {
  CANCEL = "Cancel",
  SHOW_FILTERS = "Show Filters",
  CLEAR_FILTERS = "Clear Filters",
  BACK = "Back",
  SUBMIT = "Submit",
  SEND_INVITE = "Send Invite",
  LINK = "Link",
  SAVE = "Save",
  SEARCH = "Search",
  VIEW = "View",
  REMOVE_OFFER = "Remove Offer",
  ASSOCIATE_OFFER = "Associate Offer",
  REJECT = "Reject",
  ACCEPT = "Accept",
  CREATE_COSELL = "Create Co-sell",
  CREATE_OPPORTUNITY = "Create Opportunity",
  RESYNC = "Resync",
  GET_STARTED = "Get Started",
  CREATE_PRIVATE_OFFERS = " Create Private Offer",
  PREVIOUS = "Previous Step",
  NEXT = "Next Step",
  SAVE_AS_DRAFT = "Save as Draft",
  CREATE_ADD_DIMENSION = "Add custom dimensions",
  SELECT_ALL_DIMENSION = "Select All",
  DESELECT_ALL = "Deselect All",
  SAVE_AND_PUBLISH = "Save & Publish",
  PUBLISH = "Publish",
  REVIEW = "Review Offer",
  CLONE = "Clone",
  BULK_UPLOAD = "Bulk Actions",
  SAVE_NEXT = "Save & Next",
  TEMPLATE_NEXT = "Next",
  YES = "Yes",
  NO = "No",
  SEND_EMAIL = "Send Email",
  INFO = "Info",
  ADD_RECORD_USAGE = "Add Record Usage",
  POST_USAGE = "Post Usage",
  UPDATE_FEATURE = "Update Features",
}
export enum ActionButton {
  RESET = "Reset",
  PUSH_CRM = "Push",
  REFRESH = "Refresh",
  EDIT = "Edit",
  UPDATE = "Update",
  CHANGE_STAGE = "Change Stage",
  TRANSFER = "Transfer",
  ASSOCIATE_OFFER = "Associate Offer",
  NEXT_STEP = "Next step",
  Add = "Add",
  REMOVE_OFFER = "Remove Offer",
  REPLACE_OFFER = "Replace Offer",
  LINK_CRM = "Link HubSpot Deal",
  CLOSE = "Close",
  NOTIFY_RECIPIENTS = "Add Notification Recipients",
  ADD_TAG = "Add Tag",
  ADD_Contact = "Add Customer Recipients",
  ADD_PAYMENT = "Add Payment",
}
export enum ButtonVariant {
  PRIMARY = "primary",
  SECONDARY = "secondary",
  DESTRUCTIVE = "destructive",
  TRANSPARENT = "transparent",
}
export enum ButtonSize {
  TINY = "xs",
  MEDIUM = "medium",
  SMALL = "small",
}

export enum TabVariant {
  ENCLOSED = "enclosed",
}

export enum IconVariant {
  DELETE = "delete",
  ADD = "add",
}
