export enum ModalTitle {
  UPDATE = "Update Additional Details",
  CRM = "Look Up Deal In CRM",
  STAGE = "Update Stage",
  TRANSFER = "Transfer Ownership To",
  ASSOCIATE_OFFER = "Associate AWS Marketplace offer",
  NEXT_STEP = "Add Next Step",
  EDIT_COSELL = "Edit Co-sell",
  ADD_COSELL = "Create Co-sell",
  ADD_OPPORTUNITY = "Create Opportunity",
  EDIT_OPPORTUNITY = "Edit Opportunity",
  ADD_OFFERS = "Create Private Offers",
  VIEW_DETAILS = "View Details",
  EDIT_OFFERS = "Edit Private Offer",
  REPLACE_OFFER = "Replace AWS Marketplace offer",
  REMOVE_OFFER = "Remove AWS Marketplace Offer",
  REJECT_COSELL = "Reject Co-sell",
  ACCEPT_COSELL = "Invitation Details",
  UPDATE_SAAS = "Update SaaS Documentation",
  ERROR_DETAILS = "Error Detail",
  ADD_COSELLS = "Add Co-sell",
  FILTER = "Filter",
  LINK_CRM = "Link to HubSpot Deal",
  VIEW_COSELL = "Co-sell Details",
  VIEW_OPPORTUNITY = "Opportunity Details",
  ACTIVITY_LOG = "Activity log",
  PARTNER_CONNECTION = "Multi-partner",
  PARTNER_CONNECTION_Details = "Partner Details",
  SENDER_DETAIL = "Sender Details",
  VIEW_PRIVATE_OFFERS = "Private Offer",
  SHARED_PARTNER_DETAIL = "Shared Partner Details",
  CLOSE = "Ready to close as won or lost",
  CREATE_PRIVATE_OFFER = "Create Private Offer",
  MS_CHANGE_STAGE = "Update Microsoft Stage Details",
  PROGRESS_BAR = "Progress Stages",
  SHARE_WITH_PARTNER = "Share With Partner",
  REVIEW_OFFER = "Preview Offer",
}

export enum ModalWidth {
  LARGE = "large",
  EXTRA_LARGE = "extra-large",
  MEDIUM = "md",
  SMALL = "sm",
}

export enum ModalId {
  PARTNER_CONNECTION = "partnerConnect",
  ACTION_COSELL = "modalEdit",
  ERROR_DETAILS = "errorDetails",
  LINK_CRM = "modalLinkCrm",
  ACCEPT = "accept",
  TRANSFER = "modelTransfer",
  NEXTSTEP = "modalNextStep",
  ASSOCIATE_OFFER = "modelAssociate",
  CHANGE_STAGE = "modelstage",
  VIEW_DETAILS = "viewDetails",
  CREATE_PRIVATE_OFFER = "createPrivateOffers",
  CLOUD_PROVIDER = "cloudProvider",
  LOG_PANEL = "logPanel",
  VIEW_COSELL = "viewOnSaasify",
  VIEW_PRIVATE_OFFERS = "viewPrivateOffers",
  FILTER = "filter",
  REJECT_COSELL = "rejectCoSell",
  ADD_PRIVATE_OFFER = "addPrivateOffer",
}
