export const createAceCosellTemplate = {
  Version: "3",
  Status: null,
  SellerCode: null,
  ReferenceID: null,
  DealType: null,
  CRMReferenceId: null,
  CRMOrigin: null,
  CloudProvider: null,
  CoSellEntity: {
    SoftwareRevenue: null,
    RelatedEntityIdentifiers: {
      Solutions: [],
      AWSProducts: [],
      AWSMarketplaceOffers: [],
    },
    Project: {
      Title: null,
      SalesActivities: [],
      RelatedOpportunityIdentifier: null,
      OtherCompetitorNames: null,
      ExpectedCustomerSpend: [
        {
          CurrencyCode: "USD",
          Amount: null,
          Frequency: "Monthly",
          TargetCompany: "AWS",
        },
      ],
      DeliveryModels: [],
      CustomerUseCase: null,
      CustomerBusinessProblem: null,
      CompetitorName: null,
      ApnPrograms: [],
      AdditionalComments: null,
    },
    PrimaryNeedsFromAws: [],
    PartnerOpportunityIdentifier: null,
    OpportunityType: null,
    MarketplaceTransactions: [],
    Marketing: {
      AwsFundingUsed: null,
      CampaignName: null,
      Channels: [],
      Source: null,
      UseCases: [],
    },
    LifeCycle: {
      ClosedLostReason: null,
      NextSteps: null,
      NextStepsHistory: [],
      ReviewComments: null,
      ReviewStatus: null,
      ReviewStatusReason: null,
      Stage: null,
      TargetCloseDate: "2024-12-31",
    },
    Identifier: null,
    Customer: {
      Account: {
        Address: {
          City: null,
          CountryCode: null,
          PostalCode: null,
          StateOrRegion: "",
          StreetAddress: null,
        },
        AwsAccountId: null,
        CompanyName: null,
        Duns: null,
        Industry: null,
        OtherIndustry: null,
        WebsiteUrl: null,
      },
      Contacts: [
        {
          BusinessTitle: null,
          Email: null,
          FirstName: null,
          LastName: null,
          Phone: null,
        },
      ],
    },
    CreatedDate: null,
    OpportunityTeam: [],
    NationalSecurity: "No",
  },
};
