export const createGcpCosellTemplate = {
  Version: null,
  Status: null,
  SellerCode: null,
  ReferenceID: null,
  DealType: null,
  CloudProviderIdentifier: null,
  CRMReferenceId: null,
  CRMOrigin: null,
  CloudProvider: "GCP",
  CoSellEntity: {
    name: null,
    opportunityInfo: {
      partnerEntity: null,
      indirectPartnerEntity: null,
      displayName: null,
      description: null,
      productFamily: [],
      productCategory: [],
      confidential: null,
    },
    qualificationInfo: {
      operationType: "NEW",
      contractLengthMonths: null,
      quantity: 1,
      dealSize: {
        currencyCode: null,
        units: null,
        nanos: 0,
      },
      estimatedCloseDate: {
        year: null,
        month: null,
        day: null,
      },
      publicSector: false,
      budget: "EXACT_BUDGET_GIVEN",
      authority: "CLEARLY_IDENTIFIED_PROCESS",
      need: "COMPELLING_NEED",
      timeline: "SPECIFIC_DECISION_DATES_GIVEN",
      campaignCode: null,
      legalLanguageAccepted: null,
      decisionPhase: "DECISION_PHASE_UNSPECIFIED",
    },
    customerInfo: {
      customerDetails: {
        organizationName: null,
        domain: null,
        address: {
          revision: 0,
          regionCode: "IN",
          languageCode: "EN",
          postalCode: null,
          sortingCode: null,
          administrativeArea: null,
          locality: null,
          sublocality: null,
          addressLines: [],
          recipients: null,
          organization: null,
        },
        industry: null,
        employeeCount: null,
      },
      contact: {
        givenName: null,
        familyName: null,
        email: null,
        phone: null,
      },
      region: null,
    },
    isvSolutionConnectInfo: {
      isvSolutionConnectDeal: true,
      customerContactRequested: false,
      supportLevel: null,
      contractVehicle: null,
      deliveryModel: null,
    },
    partnerInfo: {
      incentiveEligibility: false,
      incentiveType: "INCENTIVE_TYPE_UNSPECIFIED",
      contractExpiryDate: {
        year: 2025,
        month: 5,
        day: 5,
      },
      rebateExpirationDate: null,
      distributor: null,
      subBillingAccountId: null,
      extensionsCount: 10,
      gcpProjectNumbers: null,
      submittedDate: null,
      approvedDate: null,
    },
    salesCycle: {
      closeDate: null,
      partnerReadyToClose: "PARTNER_CLOSE_STAGE_UNSPECIFIED",
      closeDatePushCount: 0,
      prmSiteDetails: null,
    },
    winLossInfo: {
      lostReason: null,
      lostMainReason: null,
      lostRejectedReasonDetails: null,
      winMainReason: null,
      wonReason: null,
      winLossProducts: null,
      winLossAdditionalContext: null,
    },
    opportunityLines: [],
    opportunityTeamMembers: [],
    customerContacts: [],
    // rebateExtensions: [
    //   {
    //     requestNumber: "1",
    //     extensionReason: "OTHER_EXTENSION_REASON",
    //     extensionStatus: "SUBMITTED",
    //     extensionRejectionReason: "EXTENSION_REJECTION_REASON_UNSPECIFIED",
    //     comments: "None",
    //   },
    // ],
  },
};
