export const ampConstants = {
  overview: {
    customerName: "Customer Name",
    dealName: "Deal Name",
    referralType: "Referral Type",
    msReferralId: "Microsoft Referral ID",
    msStatus: "Microsoft Status",
    partnerStatus: "Partner Status",
    partnerStage: "Partner Stage",
  },
  customer: {
    customerName: "Customer Name",
    location: "Location",
    address1: "Address 1",
    address2: "Address 2",
    city: "City",
    state: "State",
    country: "Country",
    postalCode: "Postal Code Or Zip",
    firstName: "Customer First Name",
    lastName: "Customer Last Name",
    email: "Customer E-Mail",
    phone: "Customer Phone",
  },
  additional: {
    crmId: "CRM ID",
    campaignId: "Marketing Campaign ID",
    lostReason: "Lost Reason",
    lostReasonNotes: "Lost Reason Notes",
  },
  deal: {
    dealName: "Deal Name",
    dealType: "Deal Type",
    helpFromMicrosoft: "Help Needed From Microsoft",
    allowMsSellersView: "Would You Like Microsoft Sellers To View This Deal ?",
    purchaseIntent: "Customer Purchase Intent",
    estimatedClose: "Estimated Close Date",
    estimatedValue: "Estimated Value",
    currency: "Currency",
    solutionArea: "Solution Area",
    solutionPlay: "Solution Play",
    partnerNotes: "Partner Notes/Customer Need",
    notesToMicrosoft: "Notes To Microsoft",
  },
  upsert: {
    location: "Entire organization",
    needHelp: "No help required at this point of time",
  },
};
