import { TFunction } from "i18next";
import { t } from "i18next";
const fields = (t: TFunction) => {
  return {
    accept: {
      status: t("awsCosell.invitation.status"),
      invitationId: t("awsCosell.invitation.invitationId"),
      invitationDate: t("awsCosell.invitation.invitationDate"),
      invitationMessage: t("awsCosell.invitation.invitationMessage"),
      postalCode:t("awsCosell.invitation.postalCode"),
      country:t("awsCosell.invitation.country"),
      industryVertical: t("awsCosell.invitation.industryVertical"),
      partnerAcceptanceDeadline: t("awsCosell.invitation.partnerAcceptanceDeadline"),
      targetCloseDate: t("awsCosell.invitation.targetCloseDate"),
      estimatedAwsMonthlyRecurringRevenue:
        t("awsCosell.invitation.estimatedAwsMonthlyRecurringRevenue"),
      partnerProjectTitle: t("awsCosell.invitation.status"),
      projectDescription: "Project Description",
      businessProblem: "Business Problem",
      rejectedReason: "Rejected Reason",
      senderCompanyName: "Sender Company Name",
      senderCompanyWebsite: "Sender Company Website",
      receiverCompanyName: "Receiver Company Name",
      receiverCompanyAccountId: "Receiver Company Account Id",
      endUserCompanyName: "End User (Company Name)",
      endUserWebsite: "End User Website",
      opportunitySender: "Opportunity Sender",
    },
    additional: {
      partnerCrmUniqueIdentifier: "Partner CRM Unique Identifier",
      competitiveTracking: "Competitive Tracking",
      otherCompetitors: "Other Competitors",
      reviewStatusReason: "Review Status Reason",
      apnReviewerComments: "APN Reviewer Comments",
      awsAccountsId: "AWS Accounts ID",
      additionalComments: "Additional Comments",
      closedReason: "Closed Reason",
      awsStage: "AWS Stage",
      awsCloseDate: "AWS Close Date",
      awsClosedLostReason: "AWS Closed Lost Reason",
    },
    audit: {
      eventName: "Event Name",
      crmId: "CRM ID",
      crmName: "CRM Name",
      crmOpportunityId: "CRM Opportunity ID",
      referenceId: "Reference ID",
      coSellName: "CoSell Name",
      cloudCoSellIdentifier: "Cloud CoSell Identifier",
      schedulerAction: "Scheduler Action",
      errorMessage: "Error Message",
      providerReferenceIdentifier: "Provider Reference Identifier",
      saasifyReferenceId: "SaaSify Reference Id",
      crmReferenceId: "CRM Reference Id",
      eventProccesedTime: "Event Proccesed Time",
      requestId: "Request Id",
      originOfError: "Origin Of Error",
      userName: "User Name",
    },
    contact: {
      awsSalesRep: "AWS Sales Rep",
      partnerSalesContact: "Partner Sales Contact",
      awsAccountManager: "AWS Account Manager",
      partnerDevelopmentManager: "Partner Development Manager",
      wwpsPartnerDevelopmentManager: "WWPS Partner Development Manager",
      awsPartnerSuccessManager: "AWS Partner Success Manager (PSM)",
      awsIsvSuccessManager: "AWS ISV Success Manager (ISM)",
    },
    customer: {
      customerDuns: t("awsCosell.inputLabelMapper.customerDuns.label"),
      customerCompanyName: t(
        "awsCosell.inputLabelMapper.customerCompanyName.label"
      ),
      website: t("awsCosell.inputLabelMapper.customerWebsite.label"),
      industryVertical: t("awsCosell.inputLabelMapper.industryVertical.label"),
      otherIndustry: t("awsCosell.inputLabelMapper.otherIndustry.label"),
      streetAddress: t("awsCosell.inputLabelMapper.streetAddress.label"),
      city: t("awsCosell.inputLabelMapper.city.label"),
      state: t("awsCosell.inputLabelMapper.state.label"),
      country: t("awsCosell.inputLabelMapper.country.label"),
      postalCode: t("awsCosell.inputLabelMapper.postalCode.label"),
      opportunityOwner: t("awsCosell.customer.opportunityOwner"),
      customerFirstName: t("awsCosell.customer.customerFirstName"),
      customerLastName: t("awsCosell.customer.customerLastName"),
      customerTitle: t("awsCosell.customer.customerTitle"),
      customerPhone: t("awsCosell.customer.customerPhone"),
      customerEmail: t("awsCosell.customer.customerEmail"),
    },
    marketplace: {
      offerId: t("awsCosell.marketplace.offerId"),
      offerName: t("awsCosell.marketplace.offerName"),
      offerCreatedDate: t("awsCosell.marketplace.offerCreatedDate"),
      offerExpiryDate: t("awsCosell.marketplace.offerExpiryDate"),
    },
    overview: {
      opportunityId: t("awsCosell.overview.opportunityId"),
      customerCompanyName: t("awsCosell.overview.customerCompanyName"),
      awsMarketplaceEngagementScore: t(
        "awsCosell.overview.awsMarketplaceEngagementScore"
      ),
      opportunityOwner: t("awsCosell.overview.opportunityOwner"),
      opportunityOwnership: t("awsCosell.overview.opportunityOwnership"),
      partnerStatus: t("awsCosell.overview.partnerStatus"),
      stage: t("awsCosell.overview.stage"),
      status: t("awsCosell.overview.status"),
      awsRecommendedActions: t("awsCosell.overview.awsRecommendedActions"),
    },
    projectSegment: {
      partnerPrimaryNeed: "Partner Primary Need from AWS",
      opportunityType: "Opportunity Type",
      projectTitle: "Partner Project Title",
      parentOpportunityId: "Parent Opportunity ID",
      salesActivities: "Sales Activities",
      customerBusinessProblem: "Customer Business Problem",
      solutionsOffered: "Solutions Offered",
      awsProducts: "AWS Products",
      useCase: "Use Case",
      deliveryModel: "Delivery Model",
      estimatedAwsMRR: "Estimated AWS Monthly Recurring Revenue",
      targetCloseDate: "Target Close Date",
      apnProgram: "APN Program",
    },
    marketing: {
      opportunitySource: t("awsCosell.marketing.opportunitySource"),
      marketingCampaign:t("awsCosell.marketing.marketingCampaign"),
      marketingUseCase: t("awsCosell.marketing.marketingUseCase"),
      marketingChannel:t("awsCosell.marketing.marketingChannel"),
      marketingDevelopmentFunds: t("awsCosell.marketing.marketingDevelopmentFunds"),
      no: t("awsCosell.marketing.no"),
      yes: t("awsCosell.marketing.yes"),
      none:t("awsCosell.marketing.none"),
      marketingActivity: t("awsCosell.marketing.marketingActivity"),
    },
    saasDocumentation: {
      procurementType: "Procurement Type",
      softwareValue: "Customer Software Value",
      softwareCurrency: "Customer Software Value Currency",
      contractStartDate: "Contract Start Date",
      contractEndDate: "Contract End Date",
    },
    invitation: {
      status: "Status",
      invitationId: "Invitation Id",
      invitationDate: "Invitation Date",
      invitationMessage: "Invitation Message",
      engagementTypes: "Partner Engagement Type(s)",
      companyName: "End User (Company Name)",
      website: "End User Website",
      sender: "Opportunity Sender",
      country: "Country",
      postalCode: "Postal Code",
      industry: "Industry Vertical",
      deadline: "Partner Acceptance Deadline",
      targetCloseDate: "Target Close Date",
      estimatedAwsMRR: "Estimated AWS Monthly Recurring Revenue",
      projectTitle: "Partner Project Title",
      projectDescription: "Project Description",
      rejectionReason: "Rejected Reason",
    },
    opportunity: {
      id: "Opportunity Id",
      stage: "Opportunity Stage",
      status: "Opportunity Status",
      type: "Opportunity Type",
      targetCloseDate: "Target Close Date",
      owner: "Opportunity Owner",
      ownerEmail: "Opportunity Owner Email",
      useCase: "Use case",
      deliveryModel: "Delivery Model",
      salesActivities: "Sales Activities",
      awsProducts: "AWS Products",
      primaryNeed: "Primary need from AWS",
      solutionsOffered: "Solutions offered",
      nextSteps: "Next Steps",
    },
    alertSection: {
      apnReviewReason: "APN Review Reason :",
      apnReviewComment: "APN Review Comments :",
      rejectedReason: "Rejected Reason :",
      noReasonProvide: "No reason provided",
    },
    nextStep: {
      title: "Next Steps",
      noItems: "No Next Step History to display",
      add: "You haven't add an Next step with this opportunity.",
    },
    displayOid: {
      GCP: "Opportunity Id",
      AWS: "Identifier",
      AMP: "Microsoft Referral ID",
      separator: " : ",
    },
    noData: "No data to display",
  };
};

export const awsConstants = fields(t);
