export const awsConstants = {
  accept: {
    status: "Status",
    invitationId: "Invitation Id",
    invitationDate: "Invitation Date",
    invitationMessage: "Invitation Message",
    postalCode: "Postal Code",
    country: "Country",
    industryVertical: "Industry Vertical",
    partnerAcceptanceDeadline: "Partner Acceptance Deadline",
    targetCloseDate: "Target Close Date",
    estimatedAwsMonthlyRecurringRevenue:
      "Estimated AWS Monthly Recurring Revenue",
    partnerProjectTitle: "Partner Project Title",
    projectDescription: "Project Description",
    businessProblem: "Business Problem",
    rejectedReason: "Rejected Reason",
    senderCompanyName: "Sender Company Name",
    senderCompanyWebsite: "Sender Company Website",
    receiverCompanyName: "Receiver Company Name",
    receiverCompanyAccountId: "Receiver Company Account Id",
    endUserCompanyName: "End User (Company Name)",
    endUserWebsite: "End User Website",
    opportunitySender: "Opportunity Sender",
  },
  additional: {
    partnerCrmUniqueIdentifier: "Partner CRM Unique Identifier",
    competitiveTracking: "Competitive Tracking",
    otherCompetitors: "Other Competitors",
    reviewStatusReason: "Review Status Reason",
    apnReviewerComments: "APN Reviewer Comments",
    awsAccountsId: "AWS Accounts ID",
    additionalComments: "Additional Comments",
    closedReason: "Closed Reason",
    awsStage: "AWS Stage",
    awsCloseDate: "AWS Close Date",
    awsClosedLostReason: "AWS Closed Lost Reason",
  },
  audit: {
    eventName: "Event Name",
    crmId: "CRM ID",
    crmName: "CRM Name",
    crmOpportunityId: "CRM Opportunity ID",
    referenceId: "Reference ID",
    coSellName: "CoSell Name",
    cloudCoSellIdentifier: "Cloud CoSell Identifier",
    schedulerAction: "Scheduler Action",
    errorMessage: "Error Message",
    providerReferenceIdentifier: "Provider Reference Identifier",
    saasifyReferenceId: "SaaSify Reference Id",
    crmReferenceId: "CRM Reference Id",
    eventProccesedTime: "Event Proccesed Time",
    requestId: "Request Id",
    originOfError: "Origin Of Error",
    userName: "User Name",
  },
  contact: {
    awsSalesRep: "AWS Sales Rep",
    partnerSalesContact: "Partner Sales Contact",
    awsAccountManager: "AWS Account Manager",
    partnerDevelopmentManager: "Partner Development Manager",
    wwpsPartnerDevelopmentManager: "WWPS Partner Development Manager",
    awsPartnerSuccessManager: "AWS Partner Success Manager (PSM)",
    awsIsvSuccessManager: "AWS ISV Success Manager (ISM)",
  },
  customer: {
    customerDuns: "Customer DUNS",
    customerCompanyName: "Customer Company Name",
    website: "Website",
    industryVertical: "Industry Vertical",
    otherIndustry: "Other Industry",
    streetAddress: "Street Address",
    city: "City",
    state: "State",
    country: "Country",
    postalCode: "Postal Code",
    opportunityOwner: "Opportunity Owner",
    customerFirstName: "Customer First Name",
    customerLastName: "Customer Last Name",
    customerTitle: "Customer Title",
    customerPhone: "Customer Phone",
    customerEmail: "Customer Email",
  },
  marketplace: {
    offerId: "Offer Id",
    offerName: "Offer Name",
    offerCreatedDate: "Offer Created Date",
    offerExpiryDate: "Offer Expiry Date",
  },
  overview: {
    opportunityId: "Opportunity ID",
    customerCompanyName: "Customer Company Name",
    awsMarketplaceEngagementScore: "AWS Marketplace Engagement Score",
    opportunityOwner: "Opportunity Owner",
    opportunityOwnership: "Opportunity Ownership",
    partnerStatus: "Partner Status",
    stage: "Stage",
    status: "Status",
    awsRecommendedActions: "AWS Recommended Actions",
  },
  projectSegment: {
    partnerPrimaryNeed: "Partner Primary Need from AWS",
    opportunityType: "Opportunity Type",
    projectTitle: "Partner Project Title",
    parentOpportunityId: "Parent Opportunity ID",
    salesActivities: "Sales Activities",
    customerBusinessProblem: "Customer Business Problem",
    solutionsOffered: "Solutions Offered",
    awsProducts: "AWS Products",
    useCase: "Use Case",
    deliveryModel: "Delivery Model",
    estimatedAwsMRR: "Estimated AWS Monthly Recurring Revenue",
    targetCloseDate: "Target Close Date",
    apnProgram: "APN Program",
  },
  marketing: {
    opportunitySource: "Opportunity Source",
    marketingCampaign: "Marketing Campaign",
    marketingUseCase: "Marketing Activities Use Case",
    marketingChannel: "Marketing Activity Channel",
    marketingDevelopmentFunds: "Marketing Development Funds",
    no: "No: Marketing development funds were not used for this opportunity",
    yes: "Yes: Marketing development funds were used for this opportunity",
    none: "No: Not Sourced from marketing activity.",
    marketingActivity: "Yes: Sourced from marketing activity.",
  },
  saasDocumentation: {
    procurementType: "Procurement Type",
    softwareValue: "Customer Software Value",
    softwareCurrency: "Customer Software Value Currency",
    contractStartDate: "Contract Start Date",
    contractEndDate: "Contract End Date",
  },
  invitation: {
    status: "Status",
    invitationId: "Invitation Id",
    invitationDate: "Invitation Date",
    invitationMessage: "Invitation Message",
    engagementTypes: "Partner Engagement Type(s)",
    companyName: "End User (Company Name)",
    website: "End User Website",
    sender: "Opportunity Sender",
    country: "Country",
    postalCode: "Postal Code",
    industry: "Industry Vertical",
    deadline: "Partner Acceptance Deadline",
    targetCloseDate: "Target Close Date",
    estimatedAwsMRR: "Estimated AWS Monthly Recurring Revenue",
    projectTitle: "Partner Project Title",
    projectDescription: "Project Description",
    rejectionReason: "Rejected Reason",
  },
  opportunity: {
    id: "Opportunity Id",
    stage: "Opportunity Stage",
    status: "Opportunity Status",
    type: "Opportunity Type",
    targetCloseDate: "Target Close Date",
    owner: "Opportunity Owner",
    ownerEmail: "Opportunity Owner Email",
    useCase: "Use case",
    deliveryModel: "Delivery Model",
    salesActivities: "Sales Activities",
    awsProducts: "AWS Products",
    primaryNeed: "Primary need from AWS",
    solutionsOffered: "Solutions offered",
    nextSteps: "Next Steps",
  },
  alertSection: {
    apnReviewReason: "APN Review Reason :",
    apnReviewComment: "APN Review Comments :",
    rejectedReason: "Rejected Reason :",
    noReasonProvide: "No reason provided",
  },
  nextStep: {
    title: "Next Steps",
    noItems: "No Next Step History to display",
    add: "You haven't add an Next step with this opportunity.",
  },
  displayOid: {
    GCP: "Opportunity Id",
    AWS: "Identifier",
    AMP: "Microsoft Referral ID",
    separator: " : ",
  },
  noData:"No data to display"
};
