export const gcpConstants = {
  overview: {
    identifier: "Identifier",
    opportunityName: "Opportunity Name",
    stage: "Stage",
    status: "Status",
    customerName: "Customer Name",
    source: "Source",
    estimatedCloseDate: "Estimated Close Date",
    opportunityAmount: "Opportunity Amount",
    opportunityOwner: "Opportunity Owner",
    opportunityOwnerEmail: "Opportunity Owner Email",
    contractLength: "Contract Length (Months)",
  },
  dealQualify: {
    region: "Region",
    productFamily: "Product Family",
    estimatedTcv: "Estimated Partner Total Contract Value (TCV)",
    contractLength: "Contract Length (Months)",
    estimatedCloseDate: "Estimated Close Date",
    closeDatePushCount: "Close Date Push Count",
    decisionPhase: "Decision Phase",
    campaign: "Campaign",
    contractVehicle: "Contract Vehicle",
    deliveryModel: "Delivery Model",
    supportNeeded: "Support Needed",
    confidential: "Partner Designated Confidential",
    description: "Description",
  },
  systemInfo: {
    cloudProvider: "Cloud Provider",
    sellerAccount: "Seller Account",
    owner: "Owner",
    saasifyTracking: "Saasify Tracking",
    cloudProviderCreationDate: "Cloud Provider Creation Date",
    cloudProviderLastModified: "Cloud Provider Last Modification Date",
    createdBy: "Created By",
    creationDate: "Creation Date",
    lastModified: "Last Modification Date",
    approvedDate: "Approved Date",
  },
  customer: {
    customerName: "Customer Name",
    customerDomain: "Customer Domain",
    industry: "Industry",
    googleCustomerRecord: "Google Customer Record",
    country: "Country",
    state: "State",
    city: "City",
    postalCode: "Postal Code",
    address: "Address",
    employeeCount: "Number Of Employees",
  },
};
