export const gcpCosell = [
  {
    CloudProviderStatus: "ACCEPTED",
    CloudProviderStage: "QUALIFY",
    CloudProviderIdentifier: "SZbrHrwgXP7GI9",
    Customer: "SPEKTRA",
    OpportunityName: "New Opportunity Name GCP131",
    CreateDate: "2025-02-05T08:27:36.24",
    ModifyDate: "2025-02-05T09:04:51.86",
    RowNum: 14,
    TotalRows: 98,
    CRMMappingId: null,
    HasError: false,
    CoSellEntity: null,
    SellerCode: "6515EFD2",
    ReferenceID: "e6763fc3-ffc9-4b8f-ae6e-41c0f885b6e2",
    Status: "AcceptedByHyperScaler",
    CloudProvider: "GCP",
    ErrorMessage: [],
    CRMReferenceId: "a07Ea00001DjAeSIAV-GCP131",
    DealType: "Partner Referral",
    Version: null,
    CRMOrigin: "SalesForce",
  },
];

export const gcpCosellResponse = {
  name: "opportunities/SkaTSHuZJ3YI3v",
  customerDisplayName: "Cast AI Group",
  state: "ACCEPTED",
  stateDescription: null,
  stage: "REFINE",
  owner: "Austin McCracken",
  ownerEmail: "amccracken@google.com",
  creationDate: {
    year: 2025,
    month: 2,
    day: 13,
  },
  creatorEmail: "manesh@spektrasystems.com",
  source: "PARTNER",
  opportunityInfo: {
    partnerEntity: "partners/tf7TcI9pHs",
    indirectPartnerEntity: null,
    displayName: "Cast AI GCP Opportunity Registration Automation",
    description:
      "Connected with Cast AI to enable automated opportunity registration into Google Partner Hub from their Salesforce. Have discussed the solution details with Cast AI.",
    productFamily: ["GOOGLE_CLOUD_PLATFORM"],
    productCategory: ["PRODUCT_CATEGORY_UNSPECIFIED"],
    confidential: false,
    gcpWatermark: 0,
    opportunityAmount: {
      currencyCode: "USD",
      units: "15000",
      nanos: 0,
    },
  },
  qualificationInfo: {
    dealNumber: "DR-SkaTSHuZJ3YI3v",
    operationType: "NEW",
    contractLengthMonths: 12,
    dealSize: {
      currencyCode: "USD",
      units: "15000",
      nanos: 0,
    },
    estimatedCloseDate: {
      year: 2025,
      month: 4,
      day: 30,
    },
    publicSector: false,
    budget: "BUDGET_UNSPECIFIED",
    authority: "AUTHORITY_UNSPECIFIED",
    need: "NEED_UNSPECIFIED",
    timeline: "TIMELINE_UNSPECIFIED",
    campaignCode: null,
    msspDeal: false,
    legalLanguageAccepted: true,
    decisionPhase: "DECISION_PHASE_UNSPECIFIED",
  },
  customerInfo: {
    customerDetails: {
      organizationName: "Cast AI Group Inc",
      domain: "cast.ai",
      address: {
        revision: 0,
        regionCode: "US",
        languageCode: "en",
        postalCode: "33132",
        sortingCode: null,
        administrativeArea: "FL",
        locality: "Miami",
        sublocality: null,
        addressLines: ["111 NE 1st St fl 8 ste 1041"],
        recipients: null,
        organization: null,
      },
      industry: "SOFTWARE",
      employeeCount: 250,
    },
    contact: {
      givenName: "Zoya",
      familyName: "Bronshteyn",
      email: "zoya@cast.ai",
      phone: {
        extension: null,
        e164Number: null,
        shortCode: null,
      },
    },
    region: "NORTH_AMERICA",
  },
  isvSolutionConnectInfo: {
    isvSolutionConnectDeal: true,
    customerContactRequested: true,
    supportLevel: "ALIGN_SALES_ACCOUNT",
    contractVehicle: "UNKNOWN",
    deliveryModel: "SAAS_ON_GOOGLE_CLOUD",
  },
  partnerInfo: {
    incentiveEligibility: false,
    incentiveType: 0,
    contractExpiryDate: null,
    rebateExpirationDate: {
      year: 2025,
      month: 8,
      day: 12,
    },
    distributor: null,
    subBillingAccountId: null,
    extensionsCount: 0,
    gcpProjectNumbers: null,
    submittedDate: null,
    approvedDate: {
      year: 2025,
      month: 2,
      day: 13,
    },
  },
  salesCycle: {
    closeDate: {
      year: 2025,
      month: 4,
      day: 30,
    },
    partnerReadyToClose: 0,
    closeDatePushCount: 0,
    prmSiteDetails: null,
  },
  winLossInfo: {
    lostReason: null,
    lostMainReason: null,
    lostRejectedReasonDetails: null,
    winMainReason: null,
    wonReason: null,
    winLossProducts: null,
    winLossAdditionalContext: null,
  },
  opportunityLines: [
    {
      displayName: "oppLine1",
      quantity: 10,
      salesPrice: {
        currencyCode: "USD",
        units: "10",
        nanos: 0,
      },
      listPrice: {
        currencyCode: "USD",
        units: "15",
        nanos: 0,
      },
      totalPrice: {
        currencyCode: "USD",
        units: "20",
        nanos: 0,
      },
      metric: "units",
      description: "oppline1desc",
    },
  ],
  opportunityTeamMembers: [
    {
      name: "Denisha Ann",
      email: "anndenisha@google.com",
      accessLevel: 2,
    },
    {
      name: "Manesh Raveendran Pillai",
      email: "manesh@spektrasystems.com",
      accessLevel: 2,
    },
    {
      name: "NJ Njoku",
      email: "njoku@google.com",
      accessLevel: 2,
    },
  ],
  customerContacts: [
    {
      givenName: "Zoya",
      familyName: "Bronshteyn",
      title: null,
      role: 0,
      primary: true,
    },
  ],
  rebateExtensions: null,
  updateTime: "2025-02-18T04:36:17.369863Z",
  referenceOpportunityId: "006Kf00000KYPFDIA5",
  opportunityType: 3,
};
